apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringEcecution:
            nodeSelectorTerms:
              - matchExpression:
                 - key: node
                   operator: In
                   value:
                     - worker2
      containers:
      - name: nginx
        image: shaikmustafa/paytm:bus
