#this deploymnet file 


apiVersion: v1
kind: Deployment
metadata:
  name: mydep
  namespace: dev
spec:
  replicas: 6
  selector:
    matchLabels:
      app: yash
  template:
    metadata:
      labels:
        app: yash
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: node
                   operator: In
                   values:
                     - worker2
      containers:
         - name: mydepcon
           image: shaikmustafa/paytm:movie
           ports:
             - containerPort: 80
